### ISSUE TITLE
更新composer源,使用Aliyun

### ISSUE THREAD

**Issue by cexll** [xuanyanwow/easyswoole_admin#2]
install 时发现还是laravel,可以使用aliyun的,不然需要输入账号密码

`
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://mirrors.aliyun.com/composer/"
        }
    }
`

**Comment by cexll** [comment]
是否缺少 easyswoole ? `php easyswoole start`

**Comment by xuanyanwow** [comment]
已经更换阿里云源，不缺少easyswoole， 需要安装 。

第一步，上传源码，composer install

**Comment by xuanyanwow** [comment]
还需要按照easyswoole文档 进行easyswoole的安装。https://www.easyswoole.com/Cn/Introduction/install.html


后续会完善安装步骤文档。

**Comment by cexll** [comment]
:+1:
