### ISSUE TITLE
大兄弟，这个是什么原因？

### ISSUE THREAD

**Issue by zhoutingze** [xuanyanwow/easyswoole_admin#3]
[Swoole\Server::start(): failed to start server. Error: swServer_start_check: onTask event callback must be set at file:easyswoole_admin/vendor/easyswoole/easyswoole/src/ServerManager.php line:120]

php版本：
PHP 7.2.21 (cli) (built: Aug 27 2019 10:29:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

swoole版本

Author | Swoole Team <team@swoole.com>
Version | 4.4.4
Built | Aug 27 2019 10:39:29

**Comment by lishengwei789** [comment]
我也报了 是swoole版本的问题么

**Comment by xuanyanwow** [comment]
此问题是Easyswoole更新，需要手动适配。后续Admin项目将会兼容。
请大家先根据Easyswoole文档，更新记录，3.3.0 适配Task组件即可
